Console.WriteLine("Cidades do litoral sul de São Paulo");
Thread.Sleep(1000);
Console.WriteLine("Bertioga");
Thread.Sleep(1000);
Console.WriteLine("Cananéia");
Thread.Sleep(1000);
Console.WriteLine("Cubatão");
Thread.Sleep(1000);
Console.WriteLine("Guarujá");
Thread.Sleep(1000);
Console.WriteLine("Iguape");
Thread.Sleep(1000);
Console.WriteLine("Ilha Comprida");
Thread.Sleep(1000);
Console.WriteLine("Itanhaém");
Thread.Sleep(1000);
Console.WriteLine("Mongaguá");
Thread.Sleep(1000);
Console.WriteLine("Peruíbe");
Thread.Sleep(1000);
Console.WriteLine("Santos");
Thread.Sleep(1000);
Console.WriteLine("São Vicente");

